//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaraPayamak.ActionsServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActionsServiceReference.ActionsSoap")]
    public interface ActionsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBranchs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ActionsServiceReference.Branchs[] GetBranchs(string username, string password, int owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBranchs", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.Branchs[]> GetBranchsAsync(string username, string password, int owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBranch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int AddBranch(string username, string password, string branchName, int owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBranch", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddBranchAsync(string username, string password, string branchName, int owner);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int AddNumber(string username, string password, int branchId, string[] mobileNumbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddNumberAsync(string username, string password, int branchId, string[] mobileNumbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveBranch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int RemoveBranch(string username, string password, int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveBranch", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RemoveBranchAsync(string username, string password, int branchId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulkCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int GetBulkCount(string username, string password, int branch, string rangeFrom, string rangeTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulkCount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetBulkCountAsync(string username, string password, int branch, string rangeFrom, string rangeTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBulk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int AddBulk(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, System.DateTime DateToSend, int requestCount, int rowFrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBulk", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddBulkAsync(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, System.DateTime DateToSend, int requestCount, int rowFrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBulk2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int AddBulk2(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, string DateToSend, int requestCount, int rowFrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBulk2", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddBulk2Async(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, string DateToSend, int requestCount, int rowFrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewBulk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int AddNewBulk(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, System.DateTime DateToSend, int requestCount, int rowFrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNewBulk", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddNewBulkAsync(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, System.DateTime DateToSend, int requestCount, int rowFrom);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulkReceptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ActionsServiceReference.BulkReceptions[] GetBulkReceptions(string username, string password, int bulkId, int fromRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulkReceptions", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.BulkReceptions[]> GetBulkReceptionsAsync(string username, string password, int bulkId, int fromRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBulkDelivery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int UpdateBulkDelivery(string username, string password, int bulkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBulkDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateBulkDeliveryAsync(string username, string password, int bulkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesReceptions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ActionsServiceReference.MsgReceptions[] GetMessagesReceptions(string username, string password, long msgId, int fromRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessagesReceptions", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.MsgReceptions[]> GetMessagesReceptionsAsync(string username, string password, long msgId, int fromRows);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveBulk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int RemoveBulk(string username, string password, int bulkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveBulk", ReplyAction="*")]
        System.Threading.Tasks.Task<int> RemoveBulkAsync(string username, string password, int bulkId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulkStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ActionsServiceReference.GetBulkStatusResponse GetBulkStatus(FaraPayamak.ActionsServiceReference.GetBulkStatusRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulkStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.GetBulkStatusResponse> GetBulkStatusAsync(FaraPayamak.ActionsServiceReference.GetBulkStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalSent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int GetTotalSent(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalSent", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetTotalSentAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTodaySent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int GetTodaySent(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTodaySent", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetTodaySentAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMultipleSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ActionsServiceReference.SendMultipleSMSResponse SendMultipleSMS(FaraPayamak.ActionsServiceReference.SendMultipleSMSRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMultipleSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.SendMultipleSMSResponse> SendMultipleSMSAsync(FaraPayamak.ActionsServiceReference.SendMultipleSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMultipleSMS2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ActionsServiceReference.SendMultipleSMS2Response SendMultipleSMS2(FaraPayamak.ActionsServiceReference.SendMultipleSMS2Request request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMultipleSMS2", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.SendMultipleSMS2Response> SendMultipleSMS2Async(FaraPayamak.ActionsServiceReference.SendMultipleSMS2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMultipleSMS3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        long[] SendMultipleSMS3(string username, string password, string[] to, string from, string[] text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMultipleSMS3", ReplyAction="*")]
        System.Threading.Tasks.Task<long[]> SendMultipleSMS3Async(string username, string password, string[] to, string from, string[] text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultipleSMS3Deliveries", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int[] GetMultipleSMS3Deliveries(long[] Id, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMultipleSMS3Deliveries", ReplyAction="*")]
        System.Threading.Tasks.Task<int[]> GetMultipleSMS3DeliveriesAsync(long[] Id, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsQueue", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ActionsServiceReference.SmsQueueList GetSmsQueue(string username, string password, long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSmsQueue", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.SmsQueueList> GetSmsQueueAsync(string username, string password, long Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ActionsServiceReference.BulkGridList[] GetBulk(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBulk", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.BulkGridList[]> GetBulkAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSendBulk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        FaraPayamak.ActionsServiceReference.BulkGridList[] GetSendBulk(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSendBulk", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.BulkGridList[]> GetSendBulkAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMobileCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseBL))]
        int GetMobileCount(string username, string password, int branch, string rangeFrom, string rangeTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMobileCount", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetMobileCountAsync(string username, string password, int branch, string rangeFrom, string rangeTo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Branchs : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int branchIDField;
        
        private int numberCountField;
        
        private int branchOwnerField;
        
        private string branchNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int BranchID {
            get {
                return this.branchIDField;
            }
            set {
                this.branchIDField = value;
                this.RaisePropertyChanged("BranchID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int NumberCount {
            get {
                return this.numberCountField;
            }
            set {
                this.numberCountField = value;
                this.RaisePropertyChanged("NumberCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int BranchOwner {
            get {
                return this.branchOwnerField;
            }
            set {
                this.branchOwnerField = value;
                this.RaisePropertyChanged("BranchOwner");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
                this.RaisePropertyChanged("BranchName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BulksBL))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BulkGridList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BaseBL : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BulkGridList))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BulksBL : BaseBL {
        
        private int bulkIDField;
        
        private int userIDField;
        
        private double tariffField;
        
        private int branchIDField;
        
        private System.Nullable<System.Guid> batchIDField;
        
        private byte bulkTypeField;
        
        private byte sendTypeField;
        
        private string titleField;
        
        private string bodyField;
        
        private int bodyPartsField;
        
        private int senderField;
        
        private string rangeFromField;
        
        private string rangeToField;
        
        private int rowFromField;
        
        private byte numberRuleField;
        
        private string numberTextField;
        
        private System.DateTime scheduleDateField;
        
        private System.Nullable<System.DateTime> sentDateField;
        
        private int requestCountField;
        
        private int sentCountField;
        
        private int failedCountField;
        
        private byte periodField;
        
        private byte sendStatusField;
        
        private string descriptionsField;
        
        private string errorLogField;
        
        private byte bulkStatusField;
        
        private double creditField;
        
        private bool isMoneyBackField;
        
        private int moneyBackCountField;
        
        private int moneyBackLevelField;
        
        private string gIDField;
        
        private string cGIDField;
        
        private string fromGIDField;
        
        private bool notBlackListField;
        
        private bool notifySMSField;
        
        private string mobileNumberNotifyField;
        
        private System.Nullable<int> irancellBackCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int BulkID {
            get {
                return this.bulkIDField;
            }
            set {
                this.bulkIDField = value;
                this.RaisePropertyChanged("BulkID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
                this.RaisePropertyChanged("UserID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Tariff {
            get {
                return this.tariffField;
            }
            set {
                this.tariffField = value;
                this.RaisePropertyChanged("Tariff");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int BranchID {
            get {
                return this.branchIDField;
            }
            set {
                this.branchIDField = value;
                this.RaisePropertyChanged("BranchID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.Guid> BatchID {
            get {
                return this.batchIDField;
            }
            set {
                this.batchIDField = value;
                this.RaisePropertyChanged("BatchID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public byte BulkType {
            get {
                return this.bulkTypeField;
            }
            set {
                this.bulkTypeField = value;
                this.RaisePropertyChanged("BulkType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public byte SendType {
            get {
                return this.sendTypeField;
            }
            set {
                this.sendTypeField = value;
                this.RaisePropertyChanged("SendType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("Title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("Body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int BodyParts {
            get {
                return this.bodyPartsField;
            }
            set {
                this.bodyPartsField = value;
                this.RaisePropertyChanged("BodyParts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string RangeFrom {
            get {
                return this.rangeFromField;
            }
            set {
                this.rangeFromField = value;
                this.RaisePropertyChanged("RangeFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string RangeTo {
            get {
                return this.rangeToField;
            }
            set {
                this.rangeToField = value;
                this.RaisePropertyChanged("RangeTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int RowFrom {
            get {
                return this.rowFromField;
            }
            set {
                this.rowFromField = value;
                this.RaisePropertyChanged("RowFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public byte NumberRule {
            get {
                return this.numberRuleField;
            }
            set {
                this.numberRuleField = value;
                this.RaisePropertyChanged("NumberRule");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string NumberText {
            get {
                return this.numberTextField;
            }
            set {
                this.numberTextField = value;
                this.RaisePropertyChanged("NumberText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public System.DateTime ScheduleDate {
            get {
                return this.scheduleDateField;
            }
            set {
                this.scheduleDateField = value;
                this.RaisePropertyChanged("ScheduleDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public System.Nullable<System.DateTime> SentDate {
            get {
                return this.sentDateField;
            }
            set {
                this.sentDateField = value;
                this.RaisePropertyChanged("SentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int RequestCount {
            get {
                return this.requestCountField;
            }
            set {
                this.requestCountField = value;
                this.RaisePropertyChanged("RequestCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public int SentCount {
            get {
                return this.sentCountField;
            }
            set {
                this.sentCountField = value;
                this.RaisePropertyChanged("SentCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int FailedCount {
            get {
                return this.failedCountField;
            }
            set {
                this.failedCountField = value;
                this.RaisePropertyChanged("FailedCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public byte Period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
                this.RaisePropertyChanged("Period");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public byte SendStatus {
            get {
                return this.sendStatusField;
            }
            set {
                this.sendStatusField = value;
                this.RaisePropertyChanged("SendStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Descriptions {
            get {
                return this.descriptionsField;
            }
            set {
                this.descriptionsField = value;
                this.RaisePropertyChanged("Descriptions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ErrorLog {
            get {
                return this.errorLogField;
            }
            set {
                this.errorLogField = value;
                this.RaisePropertyChanged("ErrorLog");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public byte BulkStatus {
            get {
                return this.bulkStatusField;
            }
            set {
                this.bulkStatusField = value;
                this.RaisePropertyChanged("BulkStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public double Credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
                this.RaisePropertyChanged("Credit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public bool IsMoneyBack {
            get {
                return this.isMoneyBackField;
            }
            set {
                this.isMoneyBackField = value;
                this.RaisePropertyChanged("IsMoneyBack");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public int MoneyBackCount {
            get {
                return this.moneyBackCountField;
            }
            set {
                this.moneyBackCountField = value;
                this.RaisePropertyChanged("MoneyBackCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public int MoneyBackLevel {
            get {
                return this.moneyBackLevelField;
            }
            set {
                this.moneyBackLevelField = value;
                this.RaisePropertyChanged("MoneyBackLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string GID {
            get {
                return this.gIDField;
            }
            set {
                this.gIDField = value;
                this.RaisePropertyChanged("GID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string CGID {
            get {
                return this.cGIDField;
            }
            set {
                this.cGIDField = value;
                this.RaisePropertyChanged("CGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string FromGID {
            get {
                return this.fromGIDField;
            }
            set {
                this.fromGIDField = value;
                this.RaisePropertyChanged("FromGID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public bool NotBlackList {
            get {
                return this.notBlackListField;
            }
            set {
                this.notBlackListField = value;
                this.RaisePropertyChanged("NotBlackList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public bool NotifySMS {
            get {
                return this.notifySMSField;
            }
            set {
                this.notifySMSField = value;
                this.RaisePropertyChanged("NotifySMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string MobileNumberNotify {
            get {
                return this.mobileNumberNotifyField;
            }
            set {
                this.mobileNumberNotifyField = value;
                this.RaisePropertyChanged("MobileNumberNotify");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public System.Nullable<int> IrancellBackCount {
            get {
                return this.irancellBackCountField;
            }
            set {
                this.irancellBackCountField = value;
                this.RaisePropertyChanged("IrancellBackCount");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BulkGridList : BulksBL {
        
        private string branchNameField;
        
        private string numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
                this.RaisePropertyChanged("BranchName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SmsQueueList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private int senderField;
        
        private string bodyField;
        
        private string receiverField;
        
        private System.DateTime insertDateField;
        
        private System.Nullable<System.DateTime> fetchDateField;
        
        private byte statusField;
        
        private System.Nullable<long> recIDField;
        
        private System.Nullable<int> deliveryStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("Body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
                this.RaisePropertyChanged("Receiver");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime InsertDate {
            get {
                return this.insertDateField;
            }
            set {
                this.insertDateField = value;
                this.RaisePropertyChanged("InsertDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<System.DateTime> FetchDate {
            get {
                return this.fetchDateField;
            }
            set {
                this.fetchDateField = value;
                this.RaisePropertyChanged("FetchDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public byte Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<long> RecID {
            get {
                return this.recIDField;
            }
            set {
                this.recIDField = value;
                this.RaisePropertyChanged("RecID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<int> DeliveryStatus {
            get {
                return this.deliveryStatusField;
            }
            set {
                this.deliveryStatusField = value;
                this.RaisePropertyChanged("DeliveryStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgReceptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string recNumberField;
        
        private string sendDateField;
        
        private string recStatusField;
        
        private string deliveryStatusField;
        
        private string recIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecNumber {
            get {
                return this.recNumberField;
            }
            set {
                this.recNumberField = value;
                this.RaisePropertyChanged("RecNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
                this.RaisePropertyChanged("SendDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RecStatus {
            get {
                return this.recStatusField;
            }
            set {
                this.recStatusField = value;
                this.RaisePropertyChanged("RecStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DeliveryStatus {
            get {
                return this.deliveryStatusField;
            }
            set {
                this.deliveryStatusField = value;
                this.RaisePropertyChanged("DeliveryStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RecID {
            get {
                return this.recIDField;
            }
            set {
                this.recIDField = value;
                this.RaisePropertyChanged("RecID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BulkReceptions : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string recNumberField;
        
        private string sendDateField;
        
        private string recStatusField;
        
        private string deliveryStatusField;
        
        private string opIDField;
        
        private string bulkIDField;
        
        private string recIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RecNumber {
            get {
                return this.recNumberField;
            }
            set {
                this.recNumberField = value;
                this.RaisePropertyChanged("RecNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SendDate {
            get {
                return this.sendDateField;
            }
            set {
                this.sendDateField = value;
                this.RaisePropertyChanged("SendDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string RecStatus {
            get {
                return this.recStatusField;
            }
            set {
                this.recStatusField = value;
                this.RaisePropertyChanged("RecStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DeliveryStatus {
            get {
                return this.deliveryStatusField;
            }
            set {
                this.deliveryStatusField = value;
                this.RaisePropertyChanged("DeliveryStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string OpID {
            get {
                return this.opIDField;
            }
            set {
                this.opIDField = value;
                this.RaisePropertyChanged("OpID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BulkID {
            get {
                return this.bulkIDField;
            }
            set {
                this.bulkIDField = value;
                this.RaisePropertyChanged("BulkID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RecID {
            get {
                return this.recIDField;
            }
            set {
                this.recIDField = value;
                this.RaisePropertyChanged("RecID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkStatus", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBulkStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int bulkId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int sent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int failed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public byte status;
        
        public GetBulkStatusRequest() {
        }
        
        public GetBulkStatusRequest(string username, string password, int bulkId, int sent, int failed, byte status) {
            this.username = username;
            this.password = password;
            this.bulkId = bulkId;
            this.sent = sent;
            this.failed = failed;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBulkStatusResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBulkStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int GetBulkStatusResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int sent;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int failed;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public byte status;
        
        public GetBulkStatusResponse() {
        }
        
        public GetBulkStatusResponse(int GetBulkStatusResult, int sent, int failed, byte status) {
            this.GetBulkStatusResult = GetBulkStatusResult;
            this.sent = sent;
            this.failed = failed;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMultipleSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string[] text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string udh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendMultipleSMSRequest() {
        }
        
        public SendMultipleSMSRequest(string username, string password, string[] to, string from, string[] text, bool isflash, string udh, long[] recId, byte[] status) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMSResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMultipleSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] SendMultipleSMSResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendMultipleSMSResponse() {
        }
        
        public SendMultipleSMSResponse(int[] SendMultipleSMSResult, long[] recId, byte[] status) {
            this.SendMultipleSMSResult = SendMultipleSMSResult;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMS2", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMultipleSMS2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] to;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string[] from;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string[] text;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public bool isflash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string udh;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendMultipleSMS2Request() {
        }
        
        public SendMultipleSMS2Request(string username, string password, string[] to, string[] from, string[] text, bool isflash, string udh, long[] recId, byte[] status) {
            this.username = username;
            this.password = password;
            this.to = to;
            this.from = from;
            this.text = text;
            this.isflash = isflash;
            this.udh = udh;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMultipleSMS2Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendMultipleSMS2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int[] SendMultipleSMS2Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public long[] recId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] status;
        
        public SendMultipleSMS2Response() {
        }
        
        public SendMultipleSMS2Response(int[] SendMultipleSMS2Result, long[] recId, byte[] status) {
            this.SendMultipleSMS2Result = SendMultipleSMS2Result;
            this.recId = recId;
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ActionsSoapChannel : FaraPayamak.ActionsServiceReference.ActionsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ActionsSoapClient : System.ServiceModel.ClientBase<FaraPayamak.ActionsServiceReference.ActionsSoap>, FaraPayamak.ActionsServiceReference.ActionsSoap {
        
        public ActionsSoapClient() {
        }
        
        public ActionsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ActionsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActionsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ActionsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FaraPayamak.ActionsServiceReference.Branchs[] GetBranchs(string username, string password, int owner) {
            return base.Channel.GetBranchs(username, password, owner);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.Branchs[]> GetBranchsAsync(string username, string password, int owner) {
            return base.Channel.GetBranchsAsync(username, password, owner);
        }
        
        public int AddBranch(string username, string password, string branchName, int owner) {
            return base.Channel.AddBranch(username, password, branchName, owner);
        }
        
        public System.Threading.Tasks.Task<int> AddBranchAsync(string username, string password, string branchName, int owner) {
            return base.Channel.AddBranchAsync(username, password, branchName, owner);
        }
        
        public int AddNumber(string username, string password, int branchId, string[] mobileNumbers) {
            return base.Channel.AddNumber(username, password, branchId, mobileNumbers);
        }
        
        public System.Threading.Tasks.Task<int> AddNumberAsync(string username, string password, int branchId, string[] mobileNumbers) {
            return base.Channel.AddNumberAsync(username, password, branchId, mobileNumbers);
        }
        
        public int RemoveBranch(string username, string password, int branchId) {
            return base.Channel.RemoveBranch(username, password, branchId);
        }
        
        public System.Threading.Tasks.Task<int> RemoveBranchAsync(string username, string password, int branchId) {
            return base.Channel.RemoveBranchAsync(username, password, branchId);
        }
        
        public int GetBulkCount(string username, string password, int branch, string rangeFrom, string rangeTo) {
            return base.Channel.GetBulkCount(username, password, branch, rangeFrom, rangeTo);
        }
        
        public System.Threading.Tasks.Task<int> GetBulkCountAsync(string username, string password, int branch, string rangeFrom, string rangeTo) {
            return base.Channel.GetBulkCountAsync(username, password, branch, rangeFrom, rangeTo);
        }
        
        public int AddBulk(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, System.DateTime DateToSend, int requestCount, int rowFrom) {
            return base.Channel.AddBulk(username, password, from, branch, bulkType, title, message, rangeFrom, rangeTo, DateToSend, requestCount, rowFrom);
        }
        
        public System.Threading.Tasks.Task<int> AddBulkAsync(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, System.DateTime DateToSend, int requestCount, int rowFrom) {
            return base.Channel.AddBulkAsync(username, password, from, branch, bulkType, title, message, rangeFrom, rangeTo, DateToSend, requestCount, rowFrom);
        }
        
        public int AddBulk2(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, string DateToSend, int requestCount, int rowFrom) {
            return base.Channel.AddBulk2(username, password, from, branch, bulkType, title, message, rangeFrom, rangeTo, DateToSend, requestCount, rowFrom);
        }
        
        public System.Threading.Tasks.Task<int> AddBulk2Async(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, string DateToSend, int requestCount, int rowFrom) {
            return base.Channel.AddBulk2Async(username, password, from, branch, bulkType, title, message, rangeFrom, rangeTo, DateToSend, requestCount, rowFrom);
        }
        
        public int AddNewBulk(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, System.DateTime DateToSend, int requestCount, int rowFrom) {
            return base.Channel.AddNewBulk(username, password, from, branch, bulkType, title, message, rangeFrom, rangeTo, DateToSend, requestCount, rowFrom);
        }
        
        public System.Threading.Tasks.Task<int> AddNewBulkAsync(string username, string password, string from, int branch, byte bulkType, string title, string message, string rangeFrom, string rangeTo, System.DateTime DateToSend, int requestCount, int rowFrom) {
            return base.Channel.AddNewBulkAsync(username, password, from, branch, bulkType, title, message, rangeFrom, rangeTo, DateToSend, requestCount, rowFrom);
        }
        
        public FaraPayamak.ActionsServiceReference.BulkReceptions[] GetBulkReceptions(string username, string password, int bulkId, int fromRows) {
            return base.Channel.GetBulkReceptions(username, password, bulkId, fromRows);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.BulkReceptions[]> GetBulkReceptionsAsync(string username, string password, int bulkId, int fromRows) {
            return base.Channel.GetBulkReceptionsAsync(username, password, bulkId, fromRows);
        }
        
        public int UpdateBulkDelivery(string username, string password, int bulkId) {
            return base.Channel.UpdateBulkDelivery(username, password, bulkId);
        }
        
        public System.Threading.Tasks.Task<int> UpdateBulkDeliveryAsync(string username, string password, int bulkId) {
            return base.Channel.UpdateBulkDeliveryAsync(username, password, bulkId);
        }
        
        public FaraPayamak.ActionsServiceReference.MsgReceptions[] GetMessagesReceptions(string username, string password, long msgId, int fromRows) {
            return base.Channel.GetMessagesReceptions(username, password, msgId, fromRows);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.MsgReceptions[]> GetMessagesReceptionsAsync(string username, string password, long msgId, int fromRows) {
            return base.Channel.GetMessagesReceptionsAsync(username, password, msgId, fromRows);
        }
        
        public int RemoveBulk(string username, string password, int bulkId) {
            return base.Channel.RemoveBulk(username, password, bulkId);
        }
        
        public System.Threading.Tasks.Task<int> RemoveBulkAsync(string username, string password, int bulkId) {
            return base.Channel.RemoveBulkAsync(username, password, bulkId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FaraPayamak.ActionsServiceReference.GetBulkStatusResponse FaraPayamak.ActionsServiceReference.ActionsSoap.GetBulkStatus(FaraPayamak.ActionsServiceReference.GetBulkStatusRequest request) {
            return base.Channel.GetBulkStatus(request);
        }
        
        public int GetBulkStatus(string username, string password, int bulkId, ref int sent, ref int failed, ref byte status) {
            FaraPayamak.ActionsServiceReference.GetBulkStatusRequest inValue = new FaraPayamak.ActionsServiceReference.GetBulkStatusRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.bulkId = bulkId;
            inValue.sent = sent;
            inValue.failed = failed;
            inValue.status = status;
            FaraPayamak.ActionsServiceReference.GetBulkStatusResponse retVal = ((FaraPayamak.ActionsServiceReference.ActionsSoap)(this)).GetBulkStatus(inValue);
            sent = retVal.sent;
            failed = retVal.failed;
            status = retVal.status;
            return retVal.GetBulkStatusResult;
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.GetBulkStatusResponse> GetBulkStatusAsync(FaraPayamak.ActionsServiceReference.GetBulkStatusRequest request) {
            return base.Channel.GetBulkStatusAsync(request);
        }
        
        public int GetTotalSent(string username, string password) {
            return base.Channel.GetTotalSent(username, password);
        }
        
        public System.Threading.Tasks.Task<int> GetTotalSentAsync(string username, string password) {
            return base.Channel.GetTotalSentAsync(username, password);
        }
        
        public int GetTodaySent(string username, string password) {
            return base.Channel.GetTodaySent(username, password);
        }
        
        public System.Threading.Tasks.Task<int> GetTodaySentAsync(string username, string password) {
            return base.Channel.GetTodaySentAsync(username, password);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FaraPayamak.ActionsServiceReference.SendMultipleSMSResponse FaraPayamak.ActionsServiceReference.ActionsSoap.SendMultipleSMS(FaraPayamak.ActionsServiceReference.SendMultipleSMSRequest request) {
            return base.Channel.SendMultipleSMS(request);
        }
        
        public int[] SendMultipleSMS(string username, string password, string[] to, string from, string[] text, bool isflash, string udh, ref long[] recId, ref byte[] status) {
            FaraPayamak.ActionsServiceReference.SendMultipleSMSRequest inValue = new FaraPayamak.ActionsServiceReference.SendMultipleSMSRequest();
            inValue.username = username;
            inValue.password = password;
            inValue.to = to;
            inValue.from = from;
            inValue.text = text;
            inValue.isflash = isflash;
            inValue.udh = udh;
            inValue.recId = recId;
            inValue.status = status;
            FaraPayamak.ActionsServiceReference.SendMultipleSMSResponse retVal = ((FaraPayamak.ActionsServiceReference.ActionsSoap)(this)).SendMultipleSMS(inValue);
            recId = retVal.recId;
            status = retVal.status;
            return retVal.SendMultipleSMSResult;
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.SendMultipleSMSResponse> SendMultipleSMSAsync(FaraPayamak.ActionsServiceReference.SendMultipleSMSRequest request) {
            return base.Channel.SendMultipleSMSAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FaraPayamak.ActionsServiceReference.SendMultipleSMS2Response FaraPayamak.ActionsServiceReference.ActionsSoap.SendMultipleSMS2(FaraPayamak.ActionsServiceReference.SendMultipleSMS2Request request) {
            return base.Channel.SendMultipleSMS2(request);
        }
        
        public int[] SendMultipleSMS2(string username, string password, string[] to, string[] from, string[] text, bool isflash, string udh, ref long[] recId, ref byte[] status) {
            FaraPayamak.ActionsServiceReference.SendMultipleSMS2Request inValue = new FaraPayamak.ActionsServiceReference.SendMultipleSMS2Request();
            inValue.username = username;
            inValue.password = password;
            inValue.to = to;
            inValue.from = from;
            inValue.text = text;
            inValue.isflash = isflash;
            inValue.udh = udh;
            inValue.recId = recId;
            inValue.status = status;
            FaraPayamak.ActionsServiceReference.SendMultipleSMS2Response retVal = ((FaraPayamak.ActionsServiceReference.ActionsSoap)(this)).SendMultipleSMS2(inValue);
            recId = retVal.recId;
            status = retVal.status;
            return retVal.SendMultipleSMS2Result;
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.SendMultipleSMS2Response> SendMultipleSMS2Async(FaraPayamak.ActionsServiceReference.SendMultipleSMS2Request request) {
            return base.Channel.SendMultipleSMS2Async(request);
        }
        
        public long[] SendMultipleSMS3(string username, string password, string[] to, string from, string[] text) {
            return base.Channel.SendMultipleSMS3(username, password, to, from, text);
        }
        
        public System.Threading.Tasks.Task<long[]> SendMultipleSMS3Async(string username, string password, string[] to, string from, string[] text) {
            return base.Channel.SendMultipleSMS3Async(username, password, to, from, text);
        }
        
        public int[] GetMultipleSMS3Deliveries(long[] Id, string username, string password) {
            return base.Channel.GetMultipleSMS3Deliveries(Id, username, password);
        }
        
        public System.Threading.Tasks.Task<int[]> GetMultipleSMS3DeliveriesAsync(long[] Id, string username, string password) {
            return base.Channel.GetMultipleSMS3DeliveriesAsync(Id, username, password);
        }
        
        public FaraPayamak.ActionsServiceReference.SmsQueueList GetSmsQueue(string username, string password, long Id) {
            return base.Channel.GetSmsQueue(username, password, Id);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.SmsQueueList> GetSmsQueueAsync(string username, string password, long Id) {
            return base.Channel.GetSmsQueueAsync(username, password, Id);
        }
        
        public FaraPayamak.ActionsServiceReference.BulkGridList[] GetBulk(string username, string password) {
            return base.Channel.GetBulk(username, password);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.BulkGridList[]> GetBulkAsync(string username, string password) {
            return base.Channel.GetBulkAsync(username, password);
        }
        
        public FaraPayamak.ActionsServiceReference.BulkGridList[] GetSendBulk(string username, string password) {
            return base.Channel.GetSendBulk(username, password);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.ActionsServiceReference.BulkGridList[]> GetSendBulkAsync(string username, string password) {
            return base.Channel.GetSendBulkAsync(username, password);
        }
        
        public int GetMobileCount(string username, string password, int branch, string rangeFrom, string rangeTo) {
            return base.Channel.GetMobileCount(username, password, branch, rangeFrom, rangeTo);
        }
        
        public System.Threading.Tasks.Task<int> GetMobileCountAsync(string username, string password, int branch, string rangeFrom, string rangeTo) {
            return base.Channel.GetMobileCountAsync(username, password, branch, rangeFrom, rangeTo);
        }
    }
}
