//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaraPayamak.VoiceServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VoiceServiceReference.VoiceSoap")]
    public interface VoiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSWithSpeechText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMSWithSpeechText(string username, string password, string smsBody, string speechBody, string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSWithSpeechText", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSMSWithSpeechTextAsync(string username, string password, string smsBody, string speechBody, string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSWithSpeechTextBySchduleDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SendSMSWithSpeechTextBySchduleDate(string username, string password, string smsBody, string speechBody, string from, string to, System.DateTime scheduleDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMSWithSpeechTextBySchduleDate", ReplyAction="*")]
        System.Threading.Tasks.Task<string> SendSMSWithSpeechTextBySchduleDateAsync(string username, string password, string smsBody, string speechBody, string from, string to, System.DateTime scheduleDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSendSMSWithSpeechTextStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        FaraPayamak.VoiceServiceReference.AutoSpeechTextList GetSendSMSWithSpeechTextStatus(string username, string password, long recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSendSMSWithSpeechTextStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<FaraPayamak.VoiceServiceReference.AutoSpeechTextList> GetSendSMSWithSpeechTextStatusAsync(string username, string password, long recId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendBulkSpeechText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendBulkSpeechText(string username, string password, string title, string body, string receivers, string DateToSend, int repeatCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendBulkSpeechText", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SendBulkSpeechTextAsync(string username, string password, string title, string body, string receivers, string DateToSend, int repeatCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendBulkVoiceSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int SendBulkVoiceSMS(string username, string password, string title, int voiceFileId, string receivers, string DateToSend, int repeatCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendBulkVoiceSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SendBulkVoiceSMSAsync(string username, string password, string title, int voiceFileId, string receivers, string DateToSend, int repeatCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadVoiceFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UploadVoiceFile(string username, string password, string title, string base64StringFile);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadVoiceFile", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UploadVoiceFileAsync(string username, string password, string title, string base64StringFile);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AutoSpeechTextList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string speechBodyField;
        
        private string sMSBodyField;
        
        private string phoneNumberField;
        
        private string sMSSenderNumberField;
        
        private long sMSRecIDField;
        
        private int sMSDeliveryStatusField;
        
        private int voiceDeliveryStatusField;
        
        private int repeatVoiceField;
        
        private System.DateTime insertDateField;
        
        private byte reqStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SpeechBody {
            get {
                return this.speechBodyField;
            }
            set {
                this.speechBodyField = value;
                this.RaisePropertyChanged("SpeechBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SMSBody {
            get {
                return this.sMSBodyField;
            }
            set {
                this.sMSBodyField = value;
                this.RaisePropertyChanged("SMSBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SMSSenderNumber {
            get {
                return this.sMSSenderNumberField;
            }
            set {
                this.sMSSenderNumberField = value;
                this.RaisePropertyChanged("SMSSenderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long SMSRecID {
            get {
                return this.sMSRecIDField;
            }
            set {
                this.sMSRecIDField = value;
                this.RaisePropertyChanged("SMSRecID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int SMSDeliveryStatus {
            get {
                return this.sMSDeliveryStatusField;
            }
            set {
                this.sMSDeliveryStatusField = value;
                this.RaisePropertyChanged("SMSDeliveryStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int VoiceDeliveryStatus {
            get {
                return this.voiceDeliveryStatusField;
            }
            set {
                this.voiceDeliveryStatusField = value;
                this.RaisePropertyChanged("VoiceDeliveryStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int RepeatVoice {
            get {
                return this.repeatVoiceField;
            }
            set {
                this.repeatVoiceField = value;
                this.RaisePropertyChanged("RepeatVoice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime InsertDate {
            get {
                return this.insertDateField;
            }
            set {
                this.insertDateField = value;
                this.RaisePropertyChanged("InsertDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public byte ReqStatus {
            get {
                return this.reqStatusField;
            }
            set {
                this.reqStatusField = value;
                this.RaisePropertyChanged("ReqStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VoiceSoapChannel : FaraPayamak.VoiceServiceReference.VoiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoiceSoapClient : System.ServiceModel.ClientBase<FaraPayamak.VoiceServiceReference.VoiceSoap>, FaraPayamak.VoiceServiceReference.VoiceSoap {
        
        public VoiceSoapClient() {
        }
        
        public VoiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendSMSWithSpeechText(string username, string password, string smsBody, string speechBody, string from, string to) {
            return base.Channel.SendSMSWithSpeechText(username, password, smsBody, speechBody, from, to);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSWithSpeechTextAsync(string username, string password, string smsBody, string speechBody, string from, string to) {
            return base.Channel.SendSMSWithSpeechTextAsync(username, password, smsBody, speechBody, from, to);
        }
        
        public string SendSMSWithSpeechTextBySchduleDate(string username, string password, string smsBody, string speechBody, string from, string to, System.DateTime scheduleDate) {
            return base.Channel.SendSMSWithSpeechTextBySchduleDate(username, password, smsBody, speechBody, from, to, scheduleDate);
        }
        
        public System.Threading.Tasks.Task<string> SendSMSWithSpeechTextBySchduleDateAsync(string username, string password, string smsBody, string speechBody, string from, string to, System.DateTime scheduleDate) {
            return base.Channel.SendSMSWithSpeechTextBySchduleDateAsync(username, password, smsBody, speechBody, from, to, scheduleDate);
        }
        
        public FaraPayamak.VoiceServiceReference.AutoSpeechTextList GetSendSMSWithSpeechTextStatus(string username, string password, long recId) {
            return base.Channel.GetSendSMSWithSpeechTextStatus(username, password, recId);
        }
        
        public System.Threading.Tasks.Task<FaraPayamak.VoiceServiceReference.AutoSpeechTextList> GetSendSMSWithSpeechTextStatusAsync(string username, string password, long recId) {
            return base.Channel.GetSendSMSWithSpeechTextStatusAsync(username, password, recId);
        }
        
        public int SendBulkSpeechText(string username, string password, string title, string body, string receivers, string DateToSend, int repeatCount) {
            return base.Channel.SendBulkSpeechText(username, password, title, body, receivers, DateToSend, repeatCount);
        }
        
        public System.Threading.Tasks.Task<int> SendBulkSpeechTextAsync(string username, string password, string title, string body, string receivers, string DateToSend, int repeatCount) {
            return base.Channel.SendBulkSpeechTextAsync(username, password, title, body, receivers, DateToSend, repeatCount);
        }
        
        public int SendBulkVoiceSMS(string username, string password, string title, int voiceFileId, string receivers, string DateToSend, int repeatCount) {
            return base.Channel.SendBulkVoiceSMS(username, password, title, voiceFileId, receivers, DateToSend, repeatCount);
        }
        
        public System.Threading.Tasks.Task<int> SendBulkVoiceSMSAsync(string username, string password, string title, int voiceFileId, string receivers, string DateToSend, int repeatCount) {
            return base.Channel.SendBulkVoiceSMSAsync(username, password, title, voiceFileId, receivers, DateToSend, repeatCount);
        }
        
        public int UploadVoiceFile(string username, string password, string title, string base64StringFile) {
            return base.Channel.UploadVoiceFile(username, password, title, base64StringFile);
        }
        
        public System.Threading.Tasks.Task<int> UploadVoiceFileAsync(string username, string password, string title, string base64StringFile) {
            return base.Channel.UploadVoiceFileAsync(username, password, title, base64StringFile);
        }
    }
}
